// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCz6HD8qxr43wK5YwBMZ_XZqNSzTxKpM',
    appId: '1:927745276436:web:d9a9f77853e1a73c024501',
    messagingSenderId: '927745276436',
    projectId: 'ficcoding',
    authDomain: 'ficcoding.firebaseapp.com',
    storageBucket: 'ficcoding.appspot.com',
    measurementId: 'G-DC37BS7RWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbuoKe_2OHNMTSMi6DySsiavv2Ab6wq78',
    appId: '1:927745276436:android:9a8b1ea3c2778aef024501',
    messagingSenderId: '927745276436',
    projectId: 'ficcoding',
    storageBucket: 'ficcoding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4DigYLCWN6yaKW-NyuLq6PhnO-OYD0dc',
    appId: '1:927745276436:ios:cc6de5825641913e024501',
    messagingSenderId: '927745276436',
    projectId: 'ficcoding',
    storageBucket: 'ficcoding.appspot.com',
    iosBundleId: 'com.example.ficcoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4DigYLCWN6yaKW-NyuLq6PhnO-OYD0dc',
    appId: '1:927745276436:ios:cc6de5825641913e024501',
    messagingSenderId: '927745276436',
    projectId: 'ficcoding',
    storageBucket: 'ficcoding.appspot.com',
    iosBundleId: 'com.example.ficcoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlCz6HD8qxr43wK5YwBMZ_XZqNSzTxKpM',
    appId: '1:927745276436:web:ff14027b5c9b8312024501',
    messagingSenderId: '927745276436',
    projectId: 'ficcoding',
    authDomain: 'ficcoding.firebaseapp.com',
    storageBucket: 'ficcoding.appspot.com',
    measurementId: 'G-XNHNJE7X0P',
  );
}
